### ISSUE TITLE
Valid Templates can't be viewed when using the short form of AWS cloudformation templates

### ISSUE THREAD

**Issue by wsill** [aws/aws-toolkit-visual-studio#13]
## Expected Behavior

To be able to view templates using the short form of AWS templates. By short form I mean !Ref. I suspect it might be the ! that is causing the problem. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html

## Current Behavior

* I receive an error loading data: error parsing template file.  It appears to be on any valid template that has the !Ref in it.
* None of the stack's details are viewable

![image](https://user-images.githubusercontent.com/39839589/108609509-314d6d80-7383-11eb-8c88-327eac1079f7.png)

## Steps to Reproduce (for bugs)

Any valid template with !Ref in it

## Context

We use the short form when creating templates.

**Comment by johnwc** [comment]
Isn't short form YAML only?

**Comment by tmay57** [comment]
Supporting the short form of the Intrinsic Functions is important. We often merge in resource definitions from existing valid templates and then have them fail on the Intrinsic Functions. Folks, these short form Intrinsic Functions are documented in the AWS template documentation. They are widely used. Not supporting them in the toolkit is a barrier to adoption. This bug has been around, not even assigned, for almost two years. 

We just published a new Visual Studio Extension tool, https://lazystack.io , that ingests an OpenAPI specification and  generates a ClientSDK, Lambda projects stubs and a SAM template supporting Cognito etc. A one-click solution for all the plumbing required for a typical stack. In addition, we allow devs to merge in existing templates to expand the resources available in the stack - if  intrinsic functions are used in these external templates the AWS Toolkit publish step fails. 

I hate to do it, but I'm going to have to put in a big "Warning" note in our LazyStack docs that the toolkit doesn't support Intrinsic Function Short Forms. This makes the AWS Toolkit, which is an awesome piece of work, look a lot less polished than it otherwise is. However, I can't allow my users to run up on the rocks with this bug in the toolkit. 

If you are not going to fix this bug in a timely way, please let us know so we can allocate some time to writing a transform on our end that expands the short form into the long form when we merge in external resource specifications. This will fix the merge problem but I'm still going to have to put in the warning note or the dev will be mystified why we expanded the short forms before submitting the template to cloud formation.

**Comment by awschristou** [comment]
I have updated the issue description with an example of the current behavior.

Thank you for pinging this issue and outlining your use case @tmay57 . Can you please let me know if the yaml files you work with ever use short form in any of the following fields: `Description`, `Transform`, `Parameters`

**Comment by tmay57** [comment]
@awschristou,
Do the yaml files you work with ever use short form in any of the following fields:
Description - sure
Transform - not that I have seen
Parameters - wow, that is an interesting thought - never seen that either

Of course, the standard I'd expect is that the Serverless template should accept anything that a CloudFormation template accepts. As I understand it, the Serverless template is a superset of the CloudFormation template with macros that expand into the CloudFormation template syntax.

**Comment by awschristou** [comment]
I've made a preview build of the toolkit with some changes to the way it loads yaml based CloudFormation templates. This version should allow you to:
* view a CloudFormation stack that was created with a template that uses short form (like `!Ref`)
* deploy a yaml based CloudFormation template that contains short form

[AWSToolkitPackage.zip](https://github.com/aws/aws-toolkit-visual-studio/files/6093735/AWSToolkitPackage.zip)

If you have encountered this issue and can give this a try, I'm interested in hearing about your results.

**Comment by tmay57** [comment]
@awschristou
Thanks, I will give it a whirl this weekend and let you know.

**Comment by tmay57** [comment]
@awschristou 
I thought I'd give it a quick smoke test before calling it a day. Unfortunately, I didn't get very far:
Error parsing JSON CloudFormation Template C:\Users\tmay\LazyStackTutorial.sav\PetStore\Stacks\Dev\serverless.template: Object reference not set to an instance of an object.

The template I tested has no short forms and can be processed by the current release of the toolkit. I have attached it as a .txt file here (had to add .txt to upload it). 

[serverless.template.txt](https://github.com/aws/aws-toolkit-visual-studio/files/6094448/serverless.template.txt)

**Comment by awschristou** [comment]
Thank you for giving it a quick test @tmay57, here is a new build with a fix for that Object reference error

[AWSToolkitPackage.zip](https://github.com/aws/aws-toolkit-visual-studio/files/6104747/AWSToolkitPackage.zip)

**Comment by tmay57** [comment]
@awschristou 
I modified a couple of templates to use short forms and the new version of the extension you provided worked fine. Note that these templates contained only the following intrinsic functions: Fn::GetAtt, Fn::Sub and Ref: so only !GetAtt, !Sub and !Ref were tested.
