### ISSUE TITLE
AWSServerless .NET5 Project Model Availability Date

### ISSUE THREAD

**Issue by rd-ethicseido** [aws/aws-toolkit-visual-studio#132]
When will the AWSServerless project template .NET5 be available (to deploy an ASP.NET cross-platform site to AWS Lambda with Cloudformation)? Thank you in advance for your answer

**Comment by awschristou** [comment]
Since version 1.20.0.0 (2020-12-01), it has been possible to create Serverless Projects and start from a blueprint that leverages .NET 5

![image](https://user-images.githubusercontent.com/39839589/110153037-584e6b00-7d97-11eb-9c30-bc70a3dbb928.png)

[Release notes](https://github.com/aws/aws-toolkit-visual-studio/blob/master/CHANGELOG.md)
