### ISSUE TITLE
AWS S3 Sample project missing

### ISSUE THREAD

**Issue by niico100** [aws/aws-toolkit-visual-studio#135]
I'm following this AWS tutorial made by Amazon:
https://youtu.be/cJG-nLw0FJE?t=225

They use the AWS S3 Sample project from AWS Tools for Visual Studio

However the project no longer appears to exist. How can I access this project now from VS 2019 Community?

**Comment by awschristou** [comment]
Hi @niico100 , the sample projects have been removed from the Toolkit since that video was posted.

If you create a regular C# Console application and add NuGet package references for the AWS SDK (for example S3 is `AWSSDK.S3`), there is .NET sample code in the S3 docs that you can add to your project and explore. For example, [this page](https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingObjectKeysUsingNetSDK.html) shows how you can list the objects within an S3 bucket.

**Comment by niico100** [comment]
Not quite as super convenient but good enough thx.
