### ISSUE TITLE
Deploy from Visual Studio to AWS Beanstalk is stuck in environment's name step with Educate starter accounts

### ISSUE THREAD

**Issue by joseluisgilgil** [aws/aws-toolkit-visual-studio#142]
I am a teacher who has a lot of students with Student Starter accounts, which are limited. The students can't deploy apps from Visual Studio using AWS Toolkit.

We have set up the profile using access key and secret access of the starter account, so the AWS Explorer works fine, but when they try to publish an app, there is an error validating environment's name URL so it is impossible to continue. Please find attached screenshot.

It is Visual Studio 2019, newest version, and AWS Tookit for 2019, newest version. To reproduce the problem it is necessary to enter using a educate starter account which is limited, I think this is part of the problem.

Is there any solution or workaround?

Regards
![Screenshot_1](https://user-images.githubusercontent.com/6354234/105333160-b05d5380-5bd5-11eb-8986-9483b54af194.png)

**Comment by joseluisgilgil** [comment]
As a workaround I have also tried to create an environment using the AWS console using same student account successfuly in order to use it in Visual Studio instead of create it with the AWS Tookit.

But again there are errors. Beanstalk in toolkit say "the security token included in the request is invalid" and the created environment is not shown. It seems to be unable to read any info from beanstalk from the AWS toolkit.
![Screenshot_3](https://user-images.githubusercontent.com/6354234/105337327-940fe580-5bda-11eb-91c1-1d5904247ac8.png)
![Screenshot_2](https://user-images.githubusercontent.com/6354234/105337330-94a87c00-5bda-11eb-8f29-74d986d65910.png)

**Comment by shruti0085** [comment]
Hello joseluisgilgil, thanks for reaching out. Unfortunately, I wasn't able to reproduce the issue since I don't have access to an educate account. I want to confirm a couple things which might help us determine the source of the issue.
1. Can you confirm that the %USERPROFILE/.aws/credentials file contains values for these fields: "aws_access_key_id","aws_secret_access_key", "aws_session_token","region"? 
2. AWS Educate account providers temporary credentials that expire after a period(If I remember correctly it is 60 or 90 mins). They are generated via Amazon Security Token Service(STS). If the publish to beanstalk action occurred after 60-90 minutes of setting up the credentials, it is possible that the token was expired and hence the request was not valid. Can you try with a fresh set of temporary credentials? They can be found by clicking the "Account Details" button in vocareum.

**Comment by joseluisgilgil** [comment]
Shruti, thank you very much for your advice. Now it works fine.

It was a matter of time, as you told. I think it should be included in the AWS Toolkit docs for the students.

Regards
