### ISSUE TITLE
Upload Lambda function dialog overwrite values for Assembly/Type/Method when I enter my function name.

### ISSUE THREAD

**Issue by russau** [aws/aws-toolkit-visual-studio#146]
**Is your feature request related to a problem? Please describe.**

As I'm typing my function name into the dialog the UI is looking for matching functions. When it finds one it overwrites the values in Assembly/Type/Method.  For example with a new function start typing with "D" - the UI finds a match, overwrites the correct defaults with the values from the match. The first time this happened I didn't notice, the function got deployed with the wrong handler and threw an error when I invoked it.

![2021-02-18 12 20 15](https://user-images.githubusercontent.com/167762/108291986-5311ed80-71e7-11eb-8108-991a61b7e135.gif)

**Describe the solution you'd like**

The update of Assembly/Type/Method could happen only when there's a 100% on the function name, or wait until I've tabbed off the function name.

**Comment by awschristou** [comment]
Thanks for reaching out @russau -- in addition to overwriting those three fields, it also applies the selected function's settings to the options shown on the next page, like Role, VPC, and so on. 

We've been thinking of the following as a possible improvement, interested in your thoughts:
* replace the autocompleting the function name with a normal textbox, which doesn't update any config values
* add a button that opens a dialog which allows you to select an existing Lambda
* Selecting an existing Lambda then overwrites config fields the way the current autocomplete does

**Comment by russau** [comment]
Hello @awschristou, I'm back thinking about .net lambda again.  

Would this work: 

* Before the function name give two radio buttons  **(*) Create New Function** or **(  ) Update Existing Function**.  
* In the "create new" mode function name would be normal text box, and Assembly/Type/Method would auto generated as they are now. 
* In the "update existing" mode the function name would be a list of existing functions with a blank entry selected. Assembly/Type/Method/Role/VPC would fill in when you select a function name.  Validation would prevent you from clicking "Next" without selecting a function.
* If the `aws-lambda-tools-defaults.json` contains an existing function then the "update function" radio would be selected.

**Comment by joshongithub** [comment]
+1 

I like the idea of treating the update and create separately to improve the create new function experience.

**Comment by awschristou** [comment]
Hi @joshongithub , please use the reactions on the original post to register interest in this issue

![image](https://user-images.githubusercontent.com/39839589/161288564-b85121ca-c44c-4d1e-bfa8-2a0b259401a7.png)

**Comment by commonsensesoftware** [comment]
Honestly, there is little reason to hand type the input much of this information. There are 2 fundamental approaches to how the information can be obtained.

### Reflection
If you're using Reflection to collect this information, you can easily traverse which types and methods are compatible. There's probably a few ways the UI can be represented, but having a drop down with the Lambda type name is probably sufficient. Unless I'm mistaken a Lambda can only have a single entry point per type, which is `FunctionHandler` or `FunctionHandlerAsync`. This _should_ mean you only need to select the type.  A simple check box could be used to denote to use the asynchronous implementation. You could also inspect which method was overridden. If there's no other way to tell, then you could list each possible entry in the drop down. Once a selection is made, then you know the method, type, and assembly. There is no need to type or select additional values.

Free-form typing should simply filter the list down.  I guess you _could_ have 20 Lambdas in one assembly, but that seems unlikely. That means free-form typing may not even be necessary. The drop down would only ever contain 0-3 (ish?) choices. Even if retaining free-form search makes sense, filtering by Lambda (type) name seems like the logical thing to filter on.

It's not clear why you need to select or enter it, but you can get the **Configuration** from the `AssemblyConfigurationAttribute` and the **Framework** from `TargetFrameworkAttribute`.  This should be automatically populated or defaulted. They should should also be validated as possible targets against the runtime - if they're not already. I suspect this information may be coming from the project system to determine the output paths to pick up the assembly from.

### Source
If any part of the project system is evaluated (**Configuration** and **Framework**?), then it's possible to simply use the .NET Compiler Platform (aka Roslyn) to build a semantic model with equivalent output to using Reflection. You can figure out which types are Lambda candidates and just present the list of names.

### Updates
Updates should default to the previous state if still valid. If the names no longer exist because they were removed or renamed, it should be like you are starting a new _create_ workflow.

### Additional Information
Windows Workflow (WF) had a similar _Type Picker_ to select an `Activity`. That might be useful for inspiration. This UI essentially needs a _Type Picker_ that filters down the candidate list to available Lambda functions.

**Comment by awschristou** [comment]
We've recently released a new version of the Toolkit v1.43.0.0, with some changes to the Lambda publish dialog. The dialog now has separate options to publish to a new or existing Lambda. When you specify that you're publishing to a new lambda function, typing a function name no longer autocompletes against Lambda functions in your account. When you specify that you're publishing to an existing function, you will select from a dropdown of your account's functions. This helps avoid the scenario where function configurations adjust as you're typing a lambda function name.
