### ISSUE TITLE
Cannot create an AWS Lambda Function Project (Node.js)

### ISSUE THREAD

**Issue by simonqqsmith** [aws/aws-toolkit-visual-studio#254]
Creating a new project using the VS create project wizard selecting the AWS Lambda Function Project (Node.js) creates the project folder then just hangs indefinitely. This happens when added to an existing solution and as a new solution.

I cannot create a project for Node.js Lambdas :(

AWS Toolkit for Visual Studio 2022 v1.27.0.0 (2022-03-23)

Microsoft Visual Studio Community 2022 (2)
Version 17.2.1
VisualStudio.17.Release/17.2.1+32516.85
Microsoft .NET Framework
Version 4.8.04084

OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044

**Comment by floralph** [comment]
Thank you for bringing this to our attention.  I can confirm that I have successfully reproduced this issue within Visual Studio 20222.

**Comment by floralph** [comment]
This issue is related to the release of Visual Studio 17.2.  I have submitted a bug to Microsoft for this issue.  For further details, please see https://developercommunity.visualstudio.com/t/EnvDTESolutionTemplatePath-hangs-indef/10061221  This issue appears to only impact users of Visual Studio 17.2 and Microsoft will need to release a patch to correct the issue.

It appears that this issue occurs in all patch versions of Visual Studio 17.2 (17.2.0 - 17.2.3).  I verified that the issue does not occur in the last patch version of the last minor version, 17.1.7.

**Comment by awschristou** [comment]
Version 1.35.1.0 of the Toolkit was recently released. It contains a fix that prevents the IDE from locking up when creating a new NodeJs based Lambda function project.
