### ISSUE TITLE
AWS Toolkit extension will not install

### ISSUE THREAD

**Issue by mannyNRECA** [aws/aws-toolkit-visual-studio#316]
Windows 10 Enterprise
21H2 19044.2486

Visual Studio Professional 2022 v17.4.4

AWS Toolkit 2022 version - unknown

No install logs available.  Download the extension from VS.  Close VS.  VSIX says initializing, then it closes.  Open VS and the extension is not installed.

Attempted to download extension and run it outside VS.  Same behavior.  VSIX says initializing, then it closes.

**Comment by awschristou** [comment]
Does the VSIX installer provide a link to the installation log? That could have some details that would help find the problem.

**Comment by mannyNRECA** [comment]
I agree that would be nice.  :)  

It just closes immediately.  I don't even see an error flash.  Do you know if the logs are saved somewhere that I can access via file system?

**Comment by mannyNRECA** [comment]
I was able to install some other extension and see the correct installation behavior (a confirmation message) then verify it installed in Visual Studio.

**Comment by awschristou** [comment]
I am not sure where the log files are located. It might be that they are written into the temp folder but with a random name each time, so it could be tricky to find it.

There are a couple of different AWS Toolkit extensions. Can you confirm that you have downloaded the latest version for Visual Studio 2022 from: https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2022

Also, are you running an ARM based version of Windows?

**Comment by mannyNRECA** [comment]
No arm, Win 10 x64.  I attempted another install from the above link.  I also did the repair option on Visual Studio and after that process, it rebooted and I had the same issue with installation.

This is a new pc, new visual studio install as well.

**Comment by awschristou** [comment]
The AWS Toolkit requires administrator access and elevated privileges in order to be installed. Have you got admin access on the system? If so, can you try opening the VS Developer Command Prompt as an administrator (right click on the start menu entry and select "Run as Administrator"), and then calling the VSIX installer directly on the downloaded vsix file: 

`vsixinstaller AWSToolkitPackage.v17.vsix`

It turns out the vsix installer has a command line argument that lets you specify the log filename. So you should be able to call it with something like this, and get a log file afterwards.

`vsixinstaller /logFile:aws-toolkit-install.txt AWSToolkitPackage.v17.vsix`

You may want to put a full path for the log file. I'll be interested to know if anything changes when you try calling this from an elevated command prompt. Please attach the log if it does produce one.

**Comment by mannyNRECA** [comment]
Apparently, my local admin rights do not extend to running Visual Studio as admin.  Once I get that resolved, I'll update this issue.  Thanks!

**Comment by mannyNRECA** [comment]
That was it.  I had to explicitly open as admin to get it to install.  Thank you for your help.

**Comment by awschristou** [comment]
Thanks @mannyNRECA - glad to hear you have the extension installed. I'll make a note to have the user guide updated to mention that admin permissions are required.
