### ISSUE TITLE
There is no "AWS Empty Project" in toolkit for VS 2022 specified as per documentation

### ISSUE THREAD

**Issue by PrithiviRathinam** [aws/aws-toolkit-visual-studio#405]
Honestly, I do not know how to create a simple console application in .NET 6 that accesses AWS dynamodb service that fetches the credentials from the shared credentials file automatically during run time. I thought creating an 'AWS Empty project' would make this easier but there is no such project template in VS 2022 and having an outdated 'Getting Started' page is misleading to say the least (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/CodeSamples.DotNet.html). I do not want to hard code my access credentials like an amateur and there is no proper documentation on how to make the configuration to be loaded from file during runtime. Kindly help on the same.

**Comment by awschristou** [comment]
Hi, it looks like the page you reference has some outdated steps. I'll file an issue internally to the docs team, but you can also use the "Feedback" link on the documentation pages to share details about your experience (if documentation is unclear or outdated).

From that page, instead of selecting "AWS Empty Project" in step 4, you can use a regular "Console App" project. Then skip step 5.

You might find [this repo](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/dotnetv3/dynamodb) containing sample .NET code for working with DynamoDB handy. For a general introduction to the .NET AWS SDK, you can try out [this simple sample application](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/quick-start-s3-1-cross.html). And for a general understanding of how the AWS SDK works with credentials, [this user guide](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html) is a good starting place. Questions and issues about the AWS SDK for .NET can be posted on the SDK repo at https://github.com/aws/aws-sdk-net.
