### ISSUE TITLE
Problem installing VS 2017/2019 Toolkit

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-visual-studio#85]
Issue raised by Victor Kondin: 
https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2017&ssr=false#review-details

There are a few issues around this package:
1) If you have installed VS 2013 / 2015 and 2017/2017, vsix installer automatically refers to incorrect version (2013 / 2015) and as a result installation fails.

Proof (log from this installer):
Found installed product - Microsoft Visual Studio Professional 2015
5/3/2020 1:51:35 PM - Found installed product - Microsoft Visual Studio Community 2015
5/3/2020 1:51:35 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
5/3/2020 1:51:35 PM - Found installed product - Global Location
5/3/2020 1:51:35 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

2) Error message handling & UX during installation. When installation fails, you don't have an option to "retry". It forces you to check the logs without any further insctuctions.

**Comment by viktorkondin** [comment]
Question:
Not sure, that I still have requested log. What is the log location for AWSToolkitPackage tool ? 
Previously I just clicked on "log" button, but after using workaround - I can't access it via vsix installer.

Additional information:
- Installed Visual Studio: 2013, 2015, 2017, 2019. All of them with "Professional" subscription. 
- AWSToolkitPackage runs with "VSLauncher.exe", which was not unique for every visual studio and referred only to VS 2015
- Known workaround: I was able to install it via Visual Studio -> Extensions -> Manage Extensions.

**Comment by normj** [comment]
Hi @viktorkondin 

AWSToolkitPackage doesn't run "VSLauncher.exe". When you install Visual Studio, including 2017 and 2019, it associates the vsix file type to "VSLauncher.exe" in Windows so that "VSLauncher.exe" runs when you double click any vsix file. Out of curiosity can you search your "C:\Program Files (x86)" directory for copies of VSLauncher.exe? I'm wondering if somehow you have an old version left around that is still associated to the vsix file type. On my machine which has all versions of VS from 2013 and above I have one copy of VSLauncher.exe in the C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv directory. When I look at its properties I can see its version is 16.0.X which means it was updated when I installed version VS 2019. What is the version number you see when you look at the properties of VSLauncher.exe?

![image](https://user-images.githubusercontent.com/1653751/81148212-b4a2ed00-8f30-11ea-9194-8dfb3c582a2e.png)

**Comment by viktorkondin** [comment]
Hi @normj ,

I agree with every single and also have only 1 copy of VSLaucnher.exe in
C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv

As you correctly mentioned :
`When you install Visual Studio, including 2017 and 2019, it associates the vsix file type to "VSLauncher.exe" in Windows so that "VSLauncher.exe" runs when you double click any vsix file`.

That actually means, that VSLaucnher is always attached to one "family" of Visual studios:
2013/2015 or 2017/2019.  In other words, I assume, that one out of two aws toolkit installers won't work because of that.

`When I look at its properties I can see its version is 16.0.X which means it was updated when I installed version VS 2019. What is the version number you see when you look at the properties of VSLauncher.exe?`

Exactly, but what if you change the order of installation ?
Steps: 
1) Install VS 2019 (VSLauncher associated with VS 2019)
2) Install VS 2015 (VSLauncher associated with VS 2015)
3) Install AWS toolkit for 2017 / 2019

My current version of VSLauncher is "correct", because I deleted all Visual Studios except 2019.
![image](https://user-images.githubusercontent.com/13762206/81150327-5c97d500-8f88-11ea-8468-805b1987d54f.png)

**Comment by awschristou** [comment]
I believe this issue was caused because older Toolkit versions did not properly declare what range of Visual Studio versions they supported. We are doing this with the Toolkits for Visual Studio 2019 and newer.

With Visual Studio 2022 moving to 64 bits, all previous extensions (which are 32 bit) are also not supported by VS 2022, so it becomes a non-issue moving forward if you're using VS 2022.
